# Generated by Django 4.0 on 2022-06-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldata',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
